export default {
  Ab: "Arbrå",
  Acm: "Avesta centrum",
  Aft: "Alfta",
  Ag: "Anneberg",
  Agb: "Agnesberg",
  Ahm: "Aleholm",
  Agg: "Algutsgården",
  Aik: "Aitik",
  Ajr: "Arvidsjaur",
  Ak: "Abisko Ö",
  Alh: "Alvhem",
  Akt: "Abisko turist",
  Ali: "Arlövs industrispår",
  Al: "Arlöv",
  Alv: "Astrid Lindgrens värld",
  Am: "Almedal",
  A: "Alingsås",
  An: "Arvån",
  Alä: "Almnäs",
  Amk: "Arnemark",
  Ara: "Arnäsvall",
  Anö: "Anundsjö",
  Any: "Aneby",
  Arb: "Arboga",
  Ap: "Aspeå",
  Abb: "Abborrträsk",
  Arnc: "Arlanda",
  Apd: "Aplared",
  Arne: "Arlanda nedre",
  Arnn: "Arlanda N",
  Aal: "Annedal",
  Asd: "Aspedalen",
  Apt: "Aptas",
  Asb: "Assberg",
  Apn: "Aspen",
  Arns: "Arlanda S",
  Atp: "Attarp",
  Avk: "Almvik",
  Ar: "Arvika",
  Av: "Alvesta",
  Ax: "Axmarby",
  Bbe: "Blyberg",
  Ava: "Avaviken",
  Avky: "Avesta Krylbo",
  Ay: "Alby",
  Bdb: "Badabruk",
  Aä: "Alväng",
  Bda: "Blidstena",
  B: "Björnlunda",
  Bdn: "Boden",
  Bad: "Badsta",
  Bdf: "Bodafors",
  Bdo: "Broddbo",
  Baa: "Barkåkra",
  Bdl: "Bäckedal",
  Ben: "Bredviken",
  Bfs: "Bergfors",
  Bds: "Bodens södra",
  Bet: "Bruksberget",
  Baö: "Backsjön",
  Bdy: "Bredaryd",
  Be: "Backe",
  Bg: "Berga",
  Bf: "Brunflo",
  Bgd: "Brogården",
  Bia: "Birsta",
  Bef: "Bengtsfors",
  Bfo: "Billingsfors",
  Bgs: "Bryngenäs",
  Bkb: "Barkarby",
  Bjn: "Björnkulla",
  Bjö: "Björnsjö",
  Bgm: "Berghem",
  Bib: "Billeberga",
  Bjo: "Björketorp",
  Bid: "Björnidet",
  Bih: "Billesholm",
  Bgv: "Bälgviken",
  Bj: "Björna",
  Bjuv: "Bjuv",
  Bjy: "Björköby",
  Bhb: "Bräkne-Hoby",
  Bja: "Bjästa",
  Bl: "Ballingslöv",
  Bjb: "Björneborg",
  Bma: "Blomstermåla",
  Bhs: "Bohus",
  Bld: "Blädinge",
  Blg: "Borlänge",
  Bml: "Bromölla",
  Bjh: "Bjurhem",
  Bmb: "Blomberg",
  Bln: "Björkliden",
  Bn: "Bollnäs",
  Brd: "Brännland",
  Brh: "Brattheden",
  Bmo: "Båramo",
  Bna: "Brunna",
  Bjm: "Bjärnum",
  Brin: "Brinellskolan",
  Blv: "Burlöv",
  Bry: "Bankeryd",
  Bnk: "Blattnicksele",
  Brå: "Bjurå",
  Bre: "Bränninge",
  Brg: "Brännberg",
  Boa: "Borgstena",
  Brl: "Brålanda",
  Brk: "Brokind",
  Boda: "Boda",
  Brö: "Bredsjö",
  Brn: "Brånan",
  Bsg: "Bispgården",
  Brny: "Bro Nygård",
  Bsp: "Bestorp",
  Bog: "Bodaborg",
  Bst: "Bastuträsk",
  Bro: "Bro",
  Bof: "Bofors",
  Bsa: "Brastad",
  Bs: "Borås",
  Buk: "Brunsberg",
  Bom: "Bomansberget",
  Bor: "Bor",
  Bt: "Baggetorp",
  Btb: "Brattby",
  Bvr: "Blackvreten",
  Bsd: "Brunnsgård",
  Brs: "Brattsbacka",
  Bsä: "Bjärka-Säby",
  Bsb: "Bensjöbacken",
  Bop: "Botorp",
  Bth: "Basthagen",
  Bur: "Buresjön",
  Btg: "Bratteborg",
  Bx: "Boxholm",
  Born: "Born",
  But: "Buterud",
  Boy: "Bollebygd",
  Bp: "Brännarp",
  Bym: "Byarum",
  By: "Byvalla",
  Bva: "Barva",
  Bra: "Brista",
  Btp: "Biskopstorp",
  Btå: "Betåsen",
  Bäl: "Bällsta",
  Bål: "Bålsta",
  Bån: "Båstad",
  Bu: "Brunsbergstunneln",
  Bög: "Brännögård",
  Byä: "Byälven",
  Bud: "Buddbyn",
  Bz: "Bruzaholm",
  Dat: "Dammstorp",
  Dbn: "Degerbäcken",
  Bök: "Björkhult",
  Båp: "Brågarp",
  "Dk.hg": "Helsingör",
  Båa: "Bergåsa",
  Bön: "Bodsjön",
  "Dk.kh": "Köpenhamn H",
  Bä: "Bräcke",
  Cas: "Callans såg",
  Böo: "Björbo",
  Bäb: "Bäckebron",
  "Dk.kk": "Österport",
  "Dk.tåt": "Tårnby",
  "Dk.øre": "Örestad",
  Bäf: "Bäckefors",
  "De.ber": "Berlin",
  Cg: "Charlottenberg",
  Dfl: "Dala-Floda",
  Dn: "Dagarn",
  Dre: "Derome",
  Dns: "Dynäs",
  Dl: "Dingle",
  Ck: "Karlskrona",
  Dld: "Dals Långed",
  Dg: "Degerfors",
  Dgm: "Degermyr",
  Drt: "Dals Rostock",
  Dma: "Dannemora",
  Dgn: "Dalgränsen",
  Dy: "Dysjön",
  Crgb: "Kristianstad GBG",
  Duo: "Duvbo",
  Dt: "Dingtuna",
  Cr: "Kristianstad",
  Dis: "Diö",
  Dta: "Dorotea",
  Dgö: "Daglösen",
  Crs: "Kristianstads södra",
  Dtc: "Dorotea camping",
  Då: "Djurås",
  Diö: "Diö Norra",
  Dj: "Dala-Järna",
  Du: "Duved",
  Dån: "Dånviken",
  Ei: "Erikslund",
  D: "Degerön",
  Edv: "Edsbyverken",
  Döe: "Drömme",
  Cst: "Stockholm C",
  Döl: "Döljebro",
  Ek: "Eksjö",
  Dk: "Dockmyr",
  "Dk.cph": "Cph Airport",
  E: "Eslöv",
  Dös: "Dösjebro",
  Ea: "Eldsberga",
  Eky: "Ekeryd",
  En: "Edane",
  Em: "Emmaboda",
  Faa: "Flodala",
  Eko: "Ekolsund",
  Ebg: "Enstaberga",
  Ens: "Enafors",
  Ebk: "Edsbjörke",
  El: "Edsvalla",
  Fabg: "Falkenbergs godsstation",
  Ep: "Enköping",
  Fabp: "Falkenberg",
  Eby: "Ekeby",
  Ffl: "Frufällan",
  Er: "Ervalla",
  Fad: "Fästad",
  Ed: "Ed",
  Era: "Eneryda",
  Ffs: "Finnforsfallet",
  Fg: "Finspång",
  Eds: "Edsbyns södra",
  Fal: "Falerum",
  Erk: "Erikstad",
  Fgc: "Fagersta",
  Fiä: "Filsbäck",
  Edn: "Edsbyn",
  Fas: "Farsta strand",
  Fki: "Fjälkinge",
  Fgn: "Fagersta N",
  Fjå: "Fjällåsen",
  Fby: "Floby",
  Et: "Eskilstuna",
  Fb: "Forsbacka",
  Fc: "Framnäs city",
  Esn: "Ekenässjön",
  Fgl: "Fågelsta",
  Fgs: "Fagersanna",
  Fd: "Floda",
  Etk: "Ekträsk",
  Fkr: "Fåker",
  Fgå: "Fagerås",
  Fl: "Flädie",
  Fda: "Furudal",
  Fgö: "Fångsjöbacken",
  Fdf: "Frändefors",
  Fi: "Fiskeby",
  Flgd: "Friluftsgården",
  Flb: "Flemingsberg",
  F: "Falköping",
  Fle: "Flen",
  Feb: "Fellingsbro",
  Fhm: "Forshem",
  Feö: "Fågelsjö",
  Fdl: "Fredriksdal",
  Fa: "Finnerödja",
  Fok: "Folkesta",
  Flp: "Flackarp",
  Fln: "Falun",
  Fra: "Fristad",
  Fls: "Flisby",
  Fid: "Filipstad",
  Foo: "Foodia",
  Gbco: "Göteborg Combiterminal",
  Gb: "Göteborgs norra",
  Gbm: "Göteborg Marieholm",
  Frd: "Frinnaryd",
  Fil: "Fillan",
  Gdl: "Geijersdal",
  Fre: "Fredrikslund",
  Gia: "Gideåbacka",
  Fin: "Finja",
  Fm: "Forserum",
  Frl: "Fritsla",
  Fod: "Forsheda",
  Frå: "Frykåsen",
  Gdv: "Gröndalsviken",
  Gib: "Grillby",
  Gim: "Gimonäs",
  Fnö: "Frånö",
  Fs: "Fors",
  Gdö: "Gårdsjö",
  Gk: "Göteborg Kville",
  Gng: "Gullringen",
  Gnp: "Gnarp",
  Fsb: "Fosieby",
  Ge: "Gottne",
  Gen: "Gåsträsken",
  Fsm: "Forsmo",
  Glk: "Glommersträsk",
  Gnö: "Gnosjö",
  Gnå: "Grönåsen",
  Ggm: "Grängesbergs malmbangård",
  Glt: "Gullträsk",
  Gg: "Grängesberg",
  Gop: "Grästorp",
  Ghu: "Gula huset",
  Gp: "Gripenberg",
  Glv: "Glumslöv",
  Fsö: "Flens övre",
  Ft: "Fränsta",
  Go: "Godegård",
  Gmo: "Gimo",
  Gm: "Gemla",
  Fur: "Furet",
  Ghy: "Grythyttan",
  Gpc: "Geogr. Polcirkeln",
  Gmp: "Gamlarp",
  Gnd: "Genevad",
  Ghyn: "Grythyttans norra",
  Fvk: "Furuvik",
  Få: "Frillesås",
  Fv: "Frövi",
  Grd: "Grevaryd",
  Gms: "Grums",
  Gn: "Gnesta",
  Grö: "Grötingen",
  Gi: "Gistad",
  Gnb: "Gunnesbo",
  Gry: "Gryttje",
  Gr: "Granbergsdal",
  Grm: "Grimsås",
  Gse: "Gunsen",
  Grn: "Göringen",
  Gro: "Gubbero",
  Gnf: "Gagnef",
  Gsh: "Göteborg Skandiahamnen",
  Gäb: "Gävle godsbangård",
  Gäd: "Gärdala",
  Grs: "Gransjö",
  Gsn: "Gastsjön",
  Fär: "Fliskär",
  Gst: "Gammelstad",
  Gru: "Grundbro",
  Gss: "Gärsnäs",
  Hcp: "Hoting camping",
  Gön: "Gårdsjön",
  Gö: "Gällö",
  Gäg: "Gräsberg",
  Hd: "Halmstad",
  Haa: "Hamra",
  Gså: "Garsås",
  Hdr: "Halmstads rangerbangård",
  Hak: "Hallstavik",
  Gsv: "Göteborg Sävenäs",
  Gt: "Grimstorp",
  Hdn: "Holmsveden",
  Hdm: "Hedemora",
  Hal: "Hallinden",
  He: "Heberg",
  Har: "Harrå",
  Gtf: "Gustafs",
  Gttu: "Gamla Tortuna",
  Han: "Harasjön",
  Gtå: "Getå",
  Gua: "Gullberna",
  Gui: "Gussi",
  Hb: "Helsingborg",
  Hel: "Helenelund",
  Hes: "Helmershus",
  Gun: "Gunnarn",
  Hbd: "Högboda",
  Hf: "Hultsfred",
  Het: "Hestra",
  Hbgb: "Ramlösa",
  Hbr: "Holsbybrunn",
  Gv: "Gällivare",
  Gvo: "Göteborg Volvo",
  Hfj: "Hamrångefjärden",
  Hfa: "Hemfosa",
  Hbä: "Högbränna",
  Hfs: "Holmfors",
  Gyo: "Grycksbo",
  Gy: "Gäddmyr",
  Hks: "Hackås",
  Hfr: "Hofors",
  Hkö: "Hökön",
  Hg: "Hagaström",
  Gyt: "Gyttorp",
  Hl: "Horndal",
  Hge: "Hagge",
  Hgl: "Hagalund",
  Hlf: "Hällefors",
  Gån: "Gålnäs",
  Gä: "Gävle",
  Hgs: "Häggenås",
  Hgv: "Häggvik",
  Hlk: "Hällekis",
  Hlm: "Helgum",
  För: "Förslöv",
  Gåp: "Gåvetorp",
  "Gä.f": "Tåghallen",
  Hlr: "Horndal",
  Hgö: "Högsjö",
  "Gä.g": "Gasklockorna",
  Hlp: "Hasslarp",
  Hh: "Hallstahammar",
  Hls: "Hällnäs",
  "Gä.h": "Gävle hamn",
  G: "Göteborg",
  Hlt: "Herrhult",
  Ga: "Graninge",
  "Gä.j": "Järnvägsmuseum",
  Hie: "Hyllie",
  Hly: "Hilleby",
  Gad: "Granstanda",
  Hlv: "Hällevadsholm",
  Hp: "Haparanda",
  Hil: "Hillared",
  Hpn: "Hallsberg Posten",
  Hlö: "Hölö",
  Hr: "Herrljunga",
  Hpbg: "Hallsberg",
  Hj: "Hjulsbro",
  Hm: "Hässleholm",
  Hma: "Hökmora",
  Gal: "Gamleby",
  Gan: "Gantofta",
  Gas: "Gamlestaden",
  Hjp: "Hjärup",
  Hka: "Huskvarna",
  Hrbg: "Hallsbergs rangerbangård",
  Gau: "Garnudden",
  Hkl: "Hudiksvall",
  Hmfs: "Hissmofors",
  Hmr: "Hammar",
  Hre: "Horred",
  Hrl: "Hörle",
  Hvr: "Håverud",
  Hmö: "Holmsjö",
  Ip: "Igelstorp",
  Hvs: "Hovslätt",
  Hrm: "Hargshamn",
  In: "Insjön",
  Hnb: "Hälsingenybo",
  Hrt: "Harrträsk",
  Hnd: "Handen",
  Hs: "Hasselfors",
  Hy: "Heby",
  Hnl: "Hällenyland",
  Hyb: "Hyltebruk",
  Hno: "Hinsnoret",
  Ist: "Isätra",
  J: "Jonsered östra",
  Hyl: "Hyllstofta",
  Hnn: "Hennan",
  Hsa: "Hovsta",
  Hsb: "Hedensbyn",
  Hå: "Håsjö",
  Håg: "Harmånger",
  Ho: "Habo",
  Jbg: "Johannisberg",
  Hsk: "Hanaskog",
  Hnä: "Hälleforsnäs",
  Jb: "Järbo",
  Hsd: "Härnösand",
  Håk: "Håmojåkk",
  Hsr: "Hasslerör",
  Hål: "Hållsta",
  Jbk: "Jädersbruk",
  Hod: "Holmsund",
  Hsy: "Hussjöby",
  Hok: "Hok",
  Hsö: "Hörnsjö",
  Hä: "Hästbo",
  Hås: "Hindås",
  Hova: "Hova",
  Htg: "Hoting",
  Håp: "Håkantorp",
  Jbo: "Jordbro",
  Ht: "Hednoret",
  Jhl: "Johannedal",
  Hoå: "Holmån",
  Hto: "Hillerstorp",
  Jho: "Jakobshyttan",
  Häd: "Härad",
  Hud: "Hulingsryd",
  Jäf: "Järnforsen",
  Hu: "Huddinge",
  Jäy: "Järlövsby",
  Jk: "Jokkmokk",
  Hän: "Häggsjön",
  Häb: "Hämrasviken",
  Jö: "Jönköping",
  Hul: "Hult",
  Jkb: "Jakobsberg",
  Häp: "Häljarp",
  Hum: "Husum",
  Häy: "Härryda",
  Jögb: "Jönköpings godsbangård",
  K: "Katrineholm",
  Huö: "Hundsjön",
  Ka: "Kattarp",
  Jla: "Järlåsa",
  Humn: "Husums norra",
  Höf: "Hörnefors",
  Hö: "Höör",
  Jli: "Jamtli",
  Huv: "Huvudsta",
  Kaa: "Koijuvaara",
  Hög: "Högbysjön",
  Hv: "Hästveda",
  Jlo: "Järlebo",
  Kac: "Kalmar",
  Jn: "Järna",
  Höja: "Höja",
  Jnt: "Järneträsk",
  Hön: "Högdalen",
  Kap: "Karpalund",
  Kas: "Kalmar södra",
  Hvd: "Hjältevad",
  Jps: "Järpås",
  Hvp: "Hovmantorp",
  Jpn: "Järpen",
  Kasd: "Karlskoga Dalbacksgatan",
  Höy: "Högsby",
  Hös: "Hössjön",
  Hvn: "Hallviken",
  Kh: "Karlshamn",
  Kat: "Kattisavan",
  Kb: "Kungsbacka",
  Khe: "Hede",
  Khn: "Kristinehamn",
  Kaä: "Kattisträsk",
  Ibe: "Ivarsbjörke",
  Jr: "Järvsö",
  Id: "Iggesund",
  Kba: "Korsberga",
  Jrn: "Jörn",
  Igt: "Ingatorp",
  Khy: "Klenshyttan",
  Js: "Jämtlands Sikås",
  Ju: "Jularbo",
  Khä: "Kallhäll",
  Kbg: "Karlsborg",
  Imr: "Ingmår",
  Kbn: "Karbenning",
  Kia: "Kirunavaara",
  Kda: "Krigslida",
  Kns: "Kolsnäs",
  Kil: "Kil",
  Jv: "Jonsered",
  Kbä: "Kolbäck",
  Kn: "Knivsta",
  Jy: "Jenny",
  Jå: "Juån",
  Kid: "Kinnared",
  Jår: "Jönåker",
  Knp: "Knapptorp",
  Knl: "Knalleland",
  Kd: "Kågeröd",
  Kin: "Kinna",
  Ksu: "Kvicksund",
  Kei: "Keräsjoki",
  Kde: "Kode",
  Ksg: "Karlsberg",
  Kju: "Kjula",
  Kisa: "Kisa",
  Knä: "Knäred",
  Ke: "Karlberg",
  Kst: "Kistinge",
  Koj: "Kosjärv",
  Kit: "Kitajaur",
  Koe: "Kolke",
  Keb: "Kejsarbäcken",
  Kf: "Kortfors",
  Kjå: "Katterjåkk",
  Ksus: "Kvicksund",
  Kos: "Koskullskulle",
  Kon: "Kolmården",
  Kfn: "Kolforsen",
  Ksö: "Karsjö",
  Kl: "Klippan",
  Koä: "Korsnäs",
  Ktm: "Kaitum",
  Klbn: "Klockarbäcken",
  Kp: "Köping",
  Kt: "Kapellet",
  Kg: "Kävlinge",
  Kgd: "Kungsgården",
  Kla: "Kumla",
  Klh: "Kallholsfors",
  Kud: "Klingerud",
  Kpe: "Kaisepakte",
  Ktä: "Korsträsk",
  Kpg: "Kopparberg",
  Kgs: "Kragenäs",
  Kpkv: "Korpklev",
  Kln: "Kälarne",
  Kv: "Krokvik",
  Kll: "Källby",
  Kva: "Koskivaara",
  Kvf: "Kvillsfors",
  Kpm: "Köpmannebro",
  Klr: "Koler",
  Kr: "Killeberg",
  La: "Ludvika",
  Lab: "Lappberg",
  Kvh: "Klevshult",
  Kvi: "Kvidinge",
  Kls: "Kilafors",
  Klv: "Kilvo",
  Klx: "Kalix",
  Laov: "Laholm",
  Kvä: "Välsviken",
  Kvö: "Kvarnsjö",
  Lb: "Lingbo",
  Krb: "Karsbäcken",
  Kx: "Kalixfors",
  Km: "Kilsmo",
  Kä: "Källeryd",
  Ld: "Lindesberg",
  Krd: "Kållered",
  Kåb: "Kåbdalis",
  Krf: "Kramfors",
  Ldl: "Lidlund",
  Kri: "Karungi",
  Kå: "Kopparåsen",
  Krm: "Krokom",
  Kms: "Kimstad",
  Krl: "Kringlan",
  Kmb: "Kiruna",
  Ldo: "Lindome",
  Käb: "Kärreberga",
  Lis: "Liseberg",
  Kmy: "Kummelby",
  Lit: "Lit",
  Krn: "Krampen",
  Le: "Luleå",
  Kän: "Kungsängen",
  Lek: "Lekarekulle",
  Lj: "Ljungskile",
  Käe: "Källene",
  Kroj: "Krokom OJ",
  Lea: "Leksboda",
  Len: "Lene",
  Käp: "Käppsta",
  Kröb: "Krökesbo",
  Ks: "Karlstad",
  Kär: "Kärrgruvan",
  Les: "Lödöse Södra",
  Lju: "Ljung",
  Let: "Lilla Edet",
  Lyg: "Lyckselesågen",
  Käv: "Kälvattnet",
  Ksac: "Karlskoga centrum",
  Lys: "Lysekil",
  Köa: "Könsa",
  Lg: "Läggesta",
  Ljv: "Ljungaverk",
  Lyt: "Lycksele timmer",
  Köp: "Köpingebro",
  Ljun: "Ljungaverks lastplats",
  Kör: "Kungsör",
  Lgb: "Långbron",
  Lkm: "Lökom",
  Lyv: "Lysvik",
  Lgd: "Ledsgård",
  Lå: "Laxå",
  Lgm: "Linghem",
  Mot: "Motala",
  Låk: "Låktatjåkka",
  Lkn: "Lindekullen",
  Moy: "Mollaryd",
  Lkp: "Lidköping",
  Mp: "Mölltorp",
  Lh: "Lammhult",
  Mpb: "Persborg",
  Lkö: "Landskrona",
  Lln: "Linddalen",
  Lö: "Lörstrand",
  Lkä: "Lakaträsk",
  Löb: "Lövberga",
  Mr: "Märsta",
  Lhr: "Lillhamra",
  Lme: "Limmared",
  Lm: "Liljeholmen",
  Mrai: "Mora kommuns industrispår",
  Mra: "Mora",
  Lia: "Lillaryd",
  Lön: "Lönneberga",
  Lin: "Linaälv",
  Lmm: "Lemmeströ",
  Mras: "Morastrand",
  "Mrd.ax": "Axhult",
  M: "Malmö",
  Nkv: "Nykvarn",
  Lmn: "Långviksmon",
  Löö: "Lödöse",
  Lmo: "Löcknamon",
  Mrd: "Markaryd",
  Lms: "Lomselenäs",
  Nkt: "Näverkärret",
  Maa: "Marma",
  Lnk: "Lernacken",
  Nl: "Nelhammar",
  Mrm: "Marma",
  Mrh: "Marsvinsholm",
  Mrs: "Morshyttan",
  Nld: "Nyland",
  Ma: "Mattmar",
  Mru: "Mörrum",
  "No.hld": "Halden",
  Nml: "Niemisel",
  Lns: "Lidnäs",
  Maj: "Maj",
  Mar: "Marieholm",
  Lnå: "Lugnås",
  "No.kat": "Katterat",
  Msj: "Malmsjö",
  Lnv: "Långvattnet",
  Ms: "Mosås",
  "No.kvg": "Kongsvinger",
  Mb: "Mobodarne",
  Lo: "Lessebo",
  Msb: "Mönsterås bruk",
  "No.lil": "Lilleström",
  Mbv: "Murbergsviken",
  "No.lls": "Lilleström",
  Loka: "Loka",
  Msl: "Mellansel",
  "No.nk": "Narvik",
  Mby: "Malmby",
  Lom: "Lomsmyren",
  Msn: "Medskogsheden",
  Lp: "Linköping",
  "No.rom": "Rombak",
  Mss: "Mönsterås",
  Lot: "Lottefors",
  "No.osl": "Oslo",
  Mbä: "Malmbäck",
  Mcp: "Meselefors camping",
  Lpk: "Lappträsk",
  Msö: "Mellansjö",
  Mst: "Mariestad",
  "No.sms": "Straumsnes",
  Mdm: "Mariedamm",
  Mdl: "Moradal",
  Lr: "Lerum",
  "No.sbo": "Sarpsborg",
  Mt: "Mantorp",
  Mdn: "Mölndal",
  Lrd: "Landeryd",
  Mtm: "Maitum",
  "No.sös": "Sösterbekk",
  Mtn: "Mertainen",
  Lre: "Lästringe",
  "No.tnd": "Trondheim",
  Lrg: "Laduberg",
  Me: "Marmaverken",
  Mu: "Mullsjö",
  Mdö: "Mölndals övre",
  Noe: "Norrmjöle",
  My: "Mjölby",
  Meh: "Mehedeby",
  Mud: "Mosselund",
  Lrt: "Lerot",
  Nol: "Nol",
  Nog: "Nordmaling",
  Lrp: "Lockarp",
  Non: "Norrsjön",
  Mfj: "Mockfjärd",
  Mfn: "Munkflohögen",
  Norl: "Nordlunda",
  Ls: "Ljusdal",
  Myk: "Mölnlycke",
  Lsb: "Ljusne bruk",
  Myn: "Myrbacken",
  Mfs: "Malungsfors",
  Nosk: "Nordskogen",
  Nr: "Norrköping",
  Lse: "Ljusne",
  Lsd: "Leksand",
  Nrs: "Norrfors",
  Lsn: "Losesjön",
  Mh: "Moholm",
  Lsj: "Långsjön",
  Mgb: "Malmö godsbangård",
  Nrt: "Nuortikon",
  Lsl: "Långsele",
  Ns: "Norsesund",
  Mhn: "Myrheden",
  Lsp: "Lycksele industrispår",
  Mi: "Mörsil",
  Nsj: "Nyckelsjön",
  Lså: "Ljuså",
  Nst: "Stockholms norra",
  Nsö: "Nedansjö",
  Mia: "Maria",
  Mim: "Mimer",
  Ltj: "Lilltjära",
  Ntv: "Nattavaara",
  Ltk: "Långträsk",
  Mjv: "Morjärv",
  Mip: "Milletorp",
  Nte: "Nuorttagievlle",
  Lu: "Lund",
  Nvl: "Norra Valbo",
  Ltr: "Loster",
  Mk: "Murjek",
  Nvk: "Norrviken",
  Mkl: "Munkedal",
  Lub: "Lundby",
  Nvn: "Notviken",
  Ny: "Nyhem",
  Mkln: "Munkedals nedre",
  Mklh: "Munkedals hamn",
  Luä: "Lubboträsk",
  Ml: "Mellerud",
  Nyb: "Nybro",
  Nyf: "Nyfors",
  Lup: "Lunnarp",
  Myra: "Myra",
  Måa: "Målilla",
  Mlf: "Meselefors",
  Mlb: "Mellby",
  Må: "Morgongåva",
  Nyå: "Nyåker",
  Nyh: "Nynäshamn",
  Lvd: "Lövliden",
  Lve: "Lovene",
  Ly: "Lycksele",
  Mlg: "Malung",
  Nås: "Nås",
  Måp: "Månsarp",
  Nä: "Nälden",
  Lye: "Lyse",
  Mlgf: "Malung Folkh",
  Lyd: "Lyrestad",
  Mlgg: "Malung Gymn",
  Mäk: "Märbäck",
  Möa: "Mörlunda",
  Ot: "Ottebol",
  Mö: "Mölnbo",
  Nät: "Nättraby",
  Nöe: "Nödinge",
  Mlö: "Mellösa",
  O: "Osby",
  Of: "Olofström",
  Ob: "Ockelbo",
  Mnd: "Mariannelund",
  Mör: "Mörarp",
  Oxd: "Oxelösund",
  Ox: "Oxie",
  Möl: "Mörtsal",
  Mo: "Moheda",
  N: "Nässjö",
  Oxm: "Oxmyran",
  Nb: "Näsberg",
  Mog: "Mo grindar",
  Oh: "Oskarshamn",
  P: "Partille",
  Nba: "Nyboda",
  Om: "Oskarström",
  Nbg: "Norberg",
  Mon: "Mon",
  Mos: "Moskosel",
  Pb: "Prässebo",
  Pbg: "Persberg",
  Morp: "Munktorp",
  Pea: "Peuravaara",
  Ol: "Oleby",
  Pc: "Polcirkeln",
  Phm: "Peberholm",
  Nbr: "Nybybruk",
  Rsi: "Råtsi",
  Ope: "Ope",
  Nbt: "Norra bantorget",
  Oph: "Opphem",
  Pii: "Pitkäjärvi",
  Rsn: "Rensjön",
  Pj: "Porjus",
  Pjf: "Porjusfallen",
  Ndt: "Norrsundet",
  Orn: "Ornäs",
  Nd: "Nässundet",
  Or: "Olskroken",
  Pl: "Pilgrimstad",
  Ory: "Ormaryd",
  Rsö: "Ramsjö",
  Ors: "Orsa",
  Ndv: "Norsesund västra",
  Plm: "Pauliström",
  Rt: "Ransta",
  Pm: "Prästmon",
  Osl: "Oslättfors",
  Rte: "Röste",
  Os: "Orrskog",
  Nh: "Norsholm",
  Ngd: "Nynäsgård",
  Ng: "Norrhög",
  Rts: "Rottneros",
  Pt: "Perstorp",
  Ru: "Ragunda",
  Nhg: "Nederhögen",
  Sfl: "Säffle",
  Ptå: "Piteå",
  Osö: "Ovansjö",
  Nhr: "Norrahammar",
  På: "Pålsboda",
  Rud: "Ruda",
  Nka: "Nykroppa",
  Nk: "Nyköping",
  Sfn: "Storflon",
  Ruk: "Rundvik",
  Sg: "Stehag",
  Påa: "Påarp",
  Rum: "Runemo",
  Päb: "Piteälvsbron",
  Nkp: "Närkes Kvarntorp",
  Rus: "Runsala",
  Sgs: "Strängnäs",
  R: "Rotebro",
  Sgm: "Segmon",
  Nks: "Nyköping södra",
  Pöb: "Pölsebo",
  Nkr: "Norra Kikkejaur",
  Rut: "Rautas",
  Sgä: "Slagnäs",
  Snl: "Skanlog",
  Ram: "Ramlösa",
  Rv: "Rättvik",
  Sh: "Stjärnhov",
  Ran: "Rian",
  Ras: "Ralingsås",
  Shm: "Söderhamn",
  Snt: "Snyten",
  Shr: "Surahammar",
  Ry: "Rosshyttan",
  Rb: "Ronneby",
  Rbh: "Rabbalshede",
  Snu: "Stenungsund",
  Shv: "Söderhamn",
  Ryb: "Ryssjöbrink",
  Si: "Simrishamn",
  Rye: "Rynge",
  Snv: "Sandviken",
  Rbk: "Råbäck",
  Ryk: "Rydöbruk",
  Sif: "Sikfors",
  Sic: "Silverdalen",
  Rbä: "Repbäcken",
  Ryr: "Ryr",
  Rby: "Rockneby",
  Rbo: "Röstbo",
  Sod: "Sthlm Odenplan",
  Snö: "Stensjön",
  Soa: "Stordalen",
  So: "Solna",
  Sid: "Silverdalens bruk",
  Rym: "Rydaholm",
  Ryg: "Ryggen",
  Rd: "Rävlanda",
  Sii: "Silinge",
  Soe: "Stolpen",
  Rdg: "Rydsgård",
  Sol: "Sollentuna",
  Sik: "Svartvik",
  Råg: "Rågsveden",
  Ryä: "Rydebäck",
  Sjka: "Sjisjka",
  Rån: "Råsjön",
  Ren: "Renviken",
  Som: "Stormyran",
  Sir: "Sorsele industrispår",
  Rås: "Råskogen",
  Sop: "Skorped",
  Rf: "Rimforsa",
  Rfb: "Rimforsa brygga",
  Råö: "Rågön",
  Soö: "Storsjö",
  Räp: "Räppe",
  Sp: "Sparreholm",
  Rft: "Reftele",
  Sk: "Skövde",
  Sph: "Skeppshult",
  Rö: "Rödberg",
  Rgn: "Riksgränsen",
  Riks: "Riksgräns Swe-Dk.",
  Rön: "Rönninge",
  Skbl: "Skälebol",
  Spj: "Spjutsbygd",
  Skb: "Skinnskatteberg",
  Spjb: "Spjutbäcken",
  Rjn: "Röjan",
  Skby: "Skavstaby",
  Spk: "Sprängsviken",
  Ske: "Skee",
  Röp: "Rörstorp",
  S: "Sveg",
  Skg: "Skogås",
  Sae: "Sandared",
  "Rjn.vd": "Vemdalen",
  Rk: "Rörvik",
  Spy: "Spännarhyttan",
  Rke: "Rekarne",
  Spn: "Stolpstugan",
  Saf: "Staffanstorp",
  Spå: "Spånga",
  Skk: "Skönvik",
  Rka: "Rinkaby",
  Sarp: "Sannarp",
  Sam: "Samnan",
  Sak: "Sandbäck",
  Skl: "Skellefteå",
  Skm: "Stenkumla",
  Sre: "Söderbärke",
  Rkö: "Rocksjön",
  Sr: "Storå",
  Skn: "Skänninge",
  Rlå: "Rällså",
  Sas: "Salsta",
  Skms: "Skymossen",
  Skog: "Skoghall",
  Sau: "Stora Tuna",
  Sro: "Storebro",
  Rmh: "Rämshyttan",
  Srn: "Sörtjärn",
  Rmn: "Ramnäs",
  Saö: "Skabersjö",
  Srp: "Skurup",
  Sba: "Spannarboda",
  Rmtp: "Regumatorp",
  Skr: "Skåre",
  Skrt: "Skäret",
  Sbe: "Saluböle",
  Skrp: "Skogstorp",
  Srr: "Skattkärr",
  Skv: "Skebokvarn",
  Rob: "Roback",
  Skru: "Skållerud",
  Ros: "Rossön",
  Srs: "Sorsele",
  Srt: "Strömtorp",
  Rps: "Ripats",
  Skä: "Skästra",
  Sbi: "Storblåliden",
  Srv: "Storvreta",
  Sbk: "Stenbacken",
  Rs: "Rosersberg",
  Sl: "Sala",
  Ss: "Stenstorp",
  Stä: "Sandträsk",
  Sbl: "Skärblacka",
  Ssa: "Sjösa",
  Stö: "Strångsjö",
  Sub: "Sundbyberg",
  Slbk: "Solbacka",
  Sbu: "Strömsnäsbruk",
  Sle: "Slätte",
  Ssh: "Strömsholm",
  Sby: "Norra Sunderbyn",
  Sbä: "Sågbäcken",
  Suc: "Sundsvall",
  Sue: "Surte",
  Sst: "Stockholms södra",
  Slj: "Selsjön",
  Slg: "Sällinge",
  Slm: "Solum",
  Suf: "Sturefors",
  Sci: "Stockholm City",
  Sde: "Sköldinge",
  Sdm: "Sandmon",
  Sui: "Skuckuviken",
  Slnä: "Sellnäs",
  Sum: "Storuman",
  Ssä: "Segersäng",
  Sta: "Stuvsta",
  Sun: "Sunne",
  St: "Säter",
  Sdnä: "Sandsjönäs",
  Sm: "Sandhem",
  Sur: "Skutskär",
  Sdr: "Smålandsstenar",
  Std: "Stöde",
  Smd: "Strömstad",
  Stb: "Stångby",
  Surn: "Skutskär norra",
  Smj: "Smedjebacken",
  Sdy: "Smedby",
  Smn: "Sommen",
  Sus: "Sunderby sjh",
  Sten: "Stegsskogen",
  Ste: "Svarte",
  Sea: "Svedala",
  Suv: "Sundsvall V",
  Smo: "Strömsbro",
  Sth: "Stora Höga",
  See: "Skene",
  Stje: "Stjerneskolan",
  Smt: "Simonstorp",
  Sege: "Sege",
  Sv: "Storvik",
  Sen: "Stavreviken",
  Sti: "Storbergets industrispår",
  Stk: "Sikträsk",
  Smp: "Smedstorp",
  Sel: "Sävedalen",
  Smu: "Smålands Burseryd",
  Snb: "Snickarbo",
  Stl: "Ställdalen",
  Svc: "Svenstavik c",
  Små: "Simeå",
  Sve: "Säve",
  Sn: "Stenkullen",
  Sto: "Storträsk",
  Set: "Stensundberget",
  Stlv: "Stora Levene",
  Svg: "Svenshögen",
  Sf: "Storfors",
  Svi: "Södra Vi",
  Tdj: "Trödje",
  Sne: "Sandarne",
  Svj: "Svedje",
  Ston: "Stockviksverkens nedre",
  Teo: "Torebo",
  Svt: "Sävast",
  Stp: "Svågertorp",
  Str: "Storlien",
  Svk: "Svenstavik",
  Tdö: "Tandsjöborg",
  Sngå: "Singsån",
  Tgp: "Tågarp",
  Tet: "Tolikberget",
  Svv: "Svappavaara",
  Tåv: "Trångsviken",
  Svå: "Svartå",
  Sts: "Storsund",
  Stu: "Stugsund",
  Svö: "Skytts Vemmerlöv",
  Sy: "Stockaryd",
  Th: "Tenhult",
  Tgs: "Trångstad",
  Stv: "Stavre",
  Thl: "Tornhill",
  Syd: "Skillingaryd",
  Täl: "Tälle",
  Vga: "Vega",
  Stå: "Sollefteå",
  Vgd: "Vaggeryd",
  Thd: "Tallhed",
  Syt: "Skyttorp",
  Tö: "Tjörnarp",
  Thm: "Träskholm",
  Sån: "Stenåsen",
  Vgå: "Vårgårda",
  Sårs: "Söråkers södra",
  wGåb: "Gåshaga brygga",
  Töe: "Tösse",
  Thn: "Trollhättan",
  Vh: "Vegeholm",
  Sä: "Sävsjö",
  Säg: "Söräng",
  Töv: "Töva",
  wGåh: "Gåshaga",
  U: "Uppsala",
  Vha: "Vattholma",
  Udl: "Ulriksdal",
  Vhd: "Vagnhärad",
  Sän: "Sävastklinten",
  Säp: "Skärpan",
  wHlt: "Höglandstorget",
  Sär: "Sävenäs rangerbangård",
  Säu: "Sunnäsbruk",
  Uf: "Ulriksfors",
  Vhe: "Västerhaninge",
  Säv: "Sävenäs",
  Sävl: "Sävenäs lokstation",
  wHöb: "Högberga",
  Vhy: "Vikmanshyttan",
  Uly: "Ulvshyttan",
  Säy: "Säby",
  Vib: "Vimmerby",
  Via: "Via",
  Söc: "Södertälje C",
  Un: "Undersåker",
  Wibe: "Wibe",
  Söd: "Södertälje hamn",
  Södy: "Söderby",
  Vibh: "Vimmerby Hamra",
  Thö: "Trehörningsjö",
  Vim: "Vimnarp",
  Söka: "Södertälje kanal",
  Tim: "Timsfors",
  Vid: "V. Ingelstad",
  Una: "Uppsala norra",
  Tj: "Tjunnaryd",
  Vik: "Vikersvik",
  Söla: "Sösdala",
  Sög: "Sölvesborg",
  Tip: "Tierp",
  Upv: "Upplands Väsby",
  Sök: "Stöcke",
  Vip: "Viarp",
  Söu: "Södertälje Syd",
  Utp: "Ulvstorp",
  Tjs: "Tjugonde slussen",
  Tjsk: "Tjustskolan",
  Söv: "Skelleftehamns övre",
  Visk: "Viskan",
  Uts: "Utsikten",
  Uv: "Uddevalla",
  Tjä: "Tjärnvik",
  T: "Töreboda",
  Vj: "Vassijaure",
  Söö: "Södertälje S",
  Uvn: "Ursviken",
  Tl: "Tallåsen",
  Uå: "Umeå",
  Uågb: "Umeå godsbangård",
  Vjm: "Vojmån",
  Vk: "Västervik",
  Uåö: "Umeå östra",
  Tb: "Tillberga",
  Tag: "Taberg",
  Tlg: "Tällberg",
  Vka: "Vika",
  Tli: "Tomelilla",
  Uö: "Uddevalla Ö",
  Tba: "Tystberga",
  Tlt: "Tolita",
  wKlv: "Klövervägen",
  Vkj: "Vaikijaur",
  Vaa: "Vara",
  V: "Värnamo",
  Tm: "Tomteboda bangård",
  Tbn: "Torbacken",
  Tn: "Tannefors",
  wKoa: "Kottla",
  Vad: "Vad",
  Tbo: "Tobo",
  Tmö: "Tomteboda övre",
  Vag: "Vargön",
  wKäp: "Käppala",
  Vaj: "Varjisträsk",
  wAga: "Aga",
  Tby: "Tandsbyn",
  Tbr: "Tibro",
  Vl: "Vallsta",
  Vlb: "Vilhelmsborg",
  wLab: "Larsberg",
  Vsg: "Valskog",
  wAll: "Alléparken",
  Vld: "Vinlidsberg",
  Vsj: "Vittsjö",
  Tnk: "Torneträsk",
  Tns: "Tranås",
  wAlv: "Alvik",
  Vln: "Vallnäs",
  Vsk: "Vuonoskogen",
  wSms: "Smedslätten",
  Vb: "Varberg",
  Tnu: "Tanum",
  wBag: "Baggeby",
  To: "Torpshammar",
  wLnb: "Lundsbrunn kurort",
  wSkr: "Skärsätra",
  Vm: "Vattjom",
  Tof: "Tofta",
  Vso: "Virsbo",
  Vma: "Vilhelmina",
  wSsu: "Sissehult",
  Vbd: "Västra Bodarne",
  Vsö: "Viresjö",
  Vmat: "Vilhelmina timmer",
  Vman: "Vilhelmina norra",
  Top: "Torpåkra",
  wBod: "Bodal",
  Tot: "Toresta",
  Vta: "Vetlanda",
  Vby: "Vännäsby",
  Vme: "VME",
  Toy: "Torsby",
  Tou: "Torup",
  wBvi: "Brevik",
  Vt: "Vretstorp",
  Vto: "Västra Torup",
  Tpu: "Tappudden",
  Vn: "Värtan",
  Tp: "Teckomatorp",
  Vbä: "Verkebäck",
  Vtn: "Vattnäs",
  wNob: "Nockeby",
  Vna: "Voxna",
  Vdb: "Värmlands Bro",
  Trd: "Traryd",
  Vns: "Vännäs",
  Vdi: "Veddige",
  Vtv: "Vitvattnet",
  Vtå: "Vitåfors",
  wNot: "Nockeby torg",
  Tre: "Trekanten",
  Vdn: "Vindeln",
  wTov: "Torsvik",
  Vnt: "Vackernäset",
  Tri: "Triangeln",
  wTås: "Tallås Grusgropsväxel",
  Trg: "Trelleborg",
  Vv: "Vallvik",
  Vnö: "Vinnö",
  Vdv: "Vedevåg",
  Ve: "Väse",
  Vo: "Vansbro",
  Trm: "Trolmen",
  Vå: "Västerås",
  wOll: "Olovslund",
  Veas: "Velanda Södra",
  Trå: "Timrå",
  Våb: "Vålberg",
  Tsg: "Tågsjöberg",
  Vpm: "Varpemossen",
  Våk: "Vallåkra",
  wÅlG: "Ålstens Gård",
  Ts: "Tungelsta",
  Ved: "Vedum",
  Vr: "Vingåker",
  Vre: "Vrena",
  Tsl: "Tisselskog",
  Vrn: "Verveln",
  wRos: "Ropsten",
  Vån: "Västerås norra",
  Ttu: "Tortuna",
  Vf: "Vartofta",
  Tså: "Torsåker",
  wÅls: "Ålstensgatan",
  Vfa: "Vissefjärda",
  xFia: "Finkelboda",
  Vg: "Vänersborg",
  Vfo: "Viskafors",
  Tu: "Tumba",
  Tud: "Tunadal",
  Vrö: "Värö",
  Våv: "Västerås västra",
  Vru: "Vekerum",
  Vä: "Väring",
  Väd: "Vätteryd",
  Vs: "Vislanda",
  wSa: "Skara",
  xFie: "Fiskåsen",
  Tul: "Tullinge",
  xFla: "Flaten",
  xFl: "Fyrislund",
  xLöt: "Löt",
  Tun: "Tunneby",
  Vät: "Västra Ämtervik",
  Vän: "Vännäs norra",
  Tvb: "Tväråbäck",
  Vsd: "Vikingstad",
  Vö: "Växjö",
  Xmag: "Magnor",
  xFmö: "Forsmöllan",
  Tvä: "Tvärålund",
  Xmer: "Meråker",
  Tvd: "Torved",
  xFos: "Fredriksfors",
  Väy: "Västeraspby",
  xFsa: "Forsa",
  xFsd: "Fagersand",
  Vön: "Vassjön",
  xMfd: "Mariefred",
  Vöv: "Vinslöv",
  xMfå: "Mariefreds ångbåtsstation",
  Ty: "Tyringe",
  xA: "Anten",
  xFsu: "Frösunda",
  xFsä: "Fisksätra",
  xAkm: "Ankarsrum",
  xAlg: "Almunge",
  Tåd: "Trångsund",
  xMg: "Moga",
  Tye: "Tyllered",
  xMl: "Marielund",
  xTna: "Tuna",
  xMln: "Marielund",
  xMnb: "Molnby",
  xAlp: "Altorp",
  xGby: "Gimarpsby",
  xFåt: "Fårhult",
  xGa: "Gunsta",
  xArl: "Arelid",
  Xtnd: "Trondheim",
  xTob: "Totebo",
  xAsk: "Aska",
  xMop: "Mosstorp",
  xTog: "Tomtskog",
  xMsa: "Målilla Sanatorium",
  xB: "Bärby",
  xGhn: "Gripsholmsviken",
  xBb: "Brobacka",
  xTp: "Torpa",
  xGim: "Gimarp",
  xMus: "Munkebos",
  xGnl: "Gnötteln",
  xMyå: "Myråsen",
  xBlä: "Blägda",
  xTsk: "Trollskogen",
  xTug: "Tunagård",
  xMöb: "Mörby",
  xBn: "Bor Norra",
  xGpf: "Galoppfältet",
  xBvv: "Bråvallavägen",
  xGr: "Gräfsnäs",
  xTve: "Tveta",
  xTx: "Taxinge-Näsby",
  Xgu: "Gudå",
  xN: "Nora stad",
  xBöp: "Brösarp",
  xNbe: "Näsbyallé",
  xTås: "Tallås",
  xBäl: "Bällsta",
  xGyb: "Gyllebosjö",
  xTäb: "Täby kyrkby",
  xNbp: "Näsbypark",
  xGyt: "Gyttorp",
  xNeg: "Neglinge",
  xGåv: "Gårdveda",
  xBös: "Brösarp södra",
  xTäc: "Täby Centrum",
  xHap: "Hultarp",
  Xnk: "Narvik",
  xDje: "Djursholms Ekeby",
  xNka: "Nacka",
  xUnv: "Universitetet",
  xTäl: "Täljö",
  xDir: "Dirhuvden",
  xDkn: "Dala kvarn",
  xHbo: "Hybo",
  xNys: "Nygårds Stall Dalhem",
  xNv: "Näsviken",
  xDjö: "Djursholms Ösby",
  xVas: "Valstad",
  xUö: "Uppsala Östra",
  xHdt: "Hedlandet",
  xHed: "Henriksdal",
  xOhs: "Ohs Bruk",
  xDo: "Delsbo",
  xVbm: "Viggbyholm",
  xOta: "Ormsta",
  xEkg: "Ekskogen",
  xEkh: "Ekebohult",
  xPgn: "Pershyttevägen",
  Xhel: "Hell",
  xVbä: "Verkebäck",
  xEnb: "Enebyberg",
  xEkn: "Eken",
  xVht: "Värdshuset",
  xVen: "Vena",
  xVev: "Vendevägen",
  xPte: "Pallanite",
  xPh: "Pershyttan",
  xHgä: "Hägernäs",
  xHhf: "Hultsfreds Hembygdspark",
  xQo: "Kvarnabo",
  xRa: "Roma",
  xErn: "Ervalla NBVJ",
  xVis: "Visinge",
  xHhn: "Hjorthagen",
  xEvb: "Erstaviksbadet",
  xEsa: "Ensta",
  xRav: "Ravlundabro",
  xVir: "Virestad",
  xHjm: "Hjortöström",
  xRaä: "Ravlunda bränneri",
  xHpf: "Hultsfred (xHpf)",
  xVlt: "Vallentuna",
  xHjt: "Hjorted",
  Xrhm: "Ranheim",
  xEyd: "Elgaryd",
  xF: "Faringe",
  xRdb: "Rydbo",
  xVsm: "Virserum",
  xHkl: "Hudiksvall (xHkl)",
  xVst: "Vadstena",
  xRnb: "Roslags Näsby",
  xFb: "Funbo",
  Xhra: "Hegra",
  xVtk: "Vitaby kyrka",
  xRok: "Roma kungsgård",
  xFgr: "Fagerrör",
  xHy: "Hesselby",
  xVty: "Vitaby",
  Zöre: "Örestad",
  Xrom: "Rombakk",
  xÅbg: "Åkersberga",
  xRvä: "Ringvägen",
  Å: "Åsbro",
  xHön: "Härnön",
  xHäs: "Hultanäs",
  xVäm: "Väderum",
  Åa: "Åseda",
  xSa: "Skölsta",
  xÅbo: "Åbo",
  xHöo: "Hösjömo",
  xScs: "Scoutstugan",
  xIgb: "Igelboda",
  Åb: "Åsensbruk",
  xÅru: "Åkers Runö",
  Åba: "Ålberga",
  xSbn: "Saltsjöbaden",
  xÅtp: "Åtorp",
  xSac: "Skara camping",
  xÅs: "Årsta",
  Åbe: "Årstaberg",
  xSdn: "Saltsjö-Duvnäs",
  xIpr: "Impregneringen",
  xÄp: "Älvstorp",
  xÖdh: "Ödhult",
  xJbn: "Jagbacken",
  xSdu: "Sandudden",
  xJ: "Järle",
  Åby: "Åby",
  xJås: "Jädraås",
  xSik: "Sickla",
  xKh: "Källarhalsen",
  xÖsk: "Österskär",
  xSjv: "Sjövägen",
  xSlä: "Selknä",
  xSlu: "Slussen",
  xSjl: "Saltsjö-Järla",
  Åbyg: "Åby godsbangård",
  xÖga: "Östberga",
  xKht: "Kambshagtorp",
  Åg: "Ånge",
  xSln: "Solsidan",
  Ågy: "Ångebyn",
  Xkat: "Katterat",
  xKgl: "Kragstalund",
  xÖst: "Stockholms Östra",
  Åd: "Ådalsliden",
  Åggb: "Ånge godsbangård",
  xÖsv: "Östervik",
  xÖvl: "Östra Vemmerlöv",
  Y: "Ystad",
  Yb: "Ytterby",
  xSm: "Stora Mon",
  xKpr: "Kopperå",
  Åh: "Åshammar",
  xKår: "Kårsta",
  xSmk: "Skogsmark",
  Åhus: "Åhus",
  Ym: "Yttermalung",
  Yl: "Ytterhogdal",
  Åkg: "Årskogen",
  xSn: "Stensjön",
  xLba: "Långbacka",
  xL: "Löth",
  Åk: "Åkarp",
  xSoo: "S:t Olof",
  Yö: "Yttersjön",
  Zdro: "Drogden",
  xLbr: "Länna bruk",
  xSpä: "Spångenäs",
  Åkn: "Åkarps norra",
  xSsu: "Stocksund",
  xLgn: "Läggesta nedre",
  Ål: "Åmål",
  xSvb: "Svartbäcken Nedre",
  Åks: "Åkers styckebruk",
  Zgae: "Espergaerde",
  xLdm: "Lindholmen",
  xStä: "Storängen",
  Zhg: "Helsingör",
  Åkt: "Åskott",
  xLh: "Lövstahagen",
  xSöy: "Sjöbygget",
  Zhl: "Hellerup",
  xTab: "Tattby",
  xLhl: "Lahäll",
  Åm: "Åmsele",
  Ålg: "Ålsäng",
  xTbl: "Tibble",
  Zhum: "Humlebaek",
  xLiä: "Lillängen",
  xLjd: "Ljungbyheds grusgrop",
  xTe: "Tule",
  Åmn: "Ångsågsmossen",
  xTeg: "Tule grusgrop",
  Zkk: "Österport",
  Zkl: "Klampenborg",
  xLm: "Lilla Mon",
  Zklv: "Kalvebod",
  Åmy: "Åmyran",
  xTib: "Triabo",
  xLna: "Länna",
  Zkn: "Nörreport",
  Ånm: "Ånimskog",
  xTip: "Tippen",
  xLnb: "Lundsbrunn",
  Ö: "Örtofta",
  Ånn: "Ånn",
  Ätk: "Ättekulla",
  Ård: "Åryd",
  Äy: "Älvsbyn",
  Zok: "Kokkedal",
  Zni: "Nivå",
  xLåö: "Långsjön",
  xLäe: "Länninge",
  Åp: "Åstorp",
  Zru: "Rungsted",
  Åre: "Åre",
  Öa: "Ökna",
  Zsq: "Snekkersten",
  Öal: "Österalnö",
  Zså: "Skodsborg",
  Ztåt: "Tårnby",
  Ås: "Ås",
  Åsa: "Åsa",
  Åsal: "Åsarna central",
  Öb: "Örebro S",
  Zvb: "Vedbaek",
  Öbl: "Ösjöbol",
  Åsra: "Åsarna Södra",
  Öbn: "Örabäcken",
  Öda: "Ödåkra",
  Åst: "Åsträsk",
  Åt: "Åmotfors",
  Ög: "Ö. Grevie",
  Ögd: "Övergård",
  Åvg: "Åtvidaberg",
  Öh: "Örbyhus",
  Ä: "Ängelholm",
  Öhl: "Överhogdal",
  Öhlg: "Överhogdals grusgrop",
  Öj: "Östansjö",
  Öjr: "Öjervik",
  Ök: "Örnsköldsvik",
  Äba: "Älvboda",
  Ökn: "Örnsköldsvik norra",
  Öl: "Ölme",
  Äbg: "Ängelsberg",
  Öna: "Önaskogen",
  Äbgb: "Ängelsbergs bruk",
  Önd: "Önnestad",
  Äfs: "Äggfors",
  Ör: "Örebro",
  Örs: "Örsjö",
  Äh: "Älmhult",
  Ös: "Östersund",
  Äkb: "Älvkarleby",
  Äl: "Älgarås",
  Öso: "Ösmo",
  Öså: "Österås",
  Ösv: "Östersund V",
  Öte: "Östertälje",
  Älo: "Älvho",
  Öv: "Östavall",
  Övb: "Överby",
  Övm: "Överum",
  Äls: "Älvros",
  Övmb: "Överums Bruk",
  Övn: "Östervärn",
  Än: "Älvängen",
  Äng: "Äng",
  Övö: "Övsjö",
  Öx: "Öxnered",
  Öä: "Öreälv",
  Öäg: "Österäng",
  Änö: "Ängersjö",
  Äp: "Äppelbo",
  Äs: "Älvsjö",
  Äsb: "Älandsbro",
  Äsg: "Älvsjö godsbangård",
  Äsr: "Äskekärr",
  Sru: "Skruv",
  "Ax.br": "Axmar Bruk",
  "G.ls": "Lejonspåret",
  "Le.k": "Karlsvik",
  Rog: "Rosengård",
  XBjf: "Bjørnfjell",
  XCph: "Cph Airport",
  XKo: "Kornsjø",
  Kop: "Kronetorp",
  Kng: "Kvarnängen",
  xOxb: "Oxberg",
  xÅa: "Åseda (xÅa)",
  Vmu: "Villersmuren",
  "It.bol": "Bolzano",
  "It.ven": "Venedig",
  Fn: "Falköpings norra"
}
